### ISSUE TITLE
Get-MsIdGroupWritebackConfiguration : Additional scope needed

### ISSUE THREAD

**Issue by XeroIP** [AzureAD/MSIdentityTools#25]
Getting the following error, even when running `Connect-MgGraph` with the permissions requested:

> `Get-MsIdGroupWritebackConfiguration : Additional scope needed, call Connect-MgGraph with one of the following scopes: Directory.Read.All, Directory.ReadWrite.All, Group.Read.All, Group.ReadWrite.All, GroupMember.Read.All`

I tried connecting with all the scopes listed and just `Group.ReadWrite.All` and no matter what I would get that error. 

Looking at the code for the cmdlet, lines 66-68 read:
``` 
if (!(Compare-Object $MgPermissions.Name -DifferenceObject $MgContext.Scopes -ExcludeDifferent)) {
    Write-Error "Additional scope needed, call Connect-MgGraph with one of the following scopes: $($MgPermissions.Name -join ', ')" -ErrorAction Stop
}
```

I would expect that if `-ExcludeDifferent` is used, then so should `-IncludeEqual`. I made that change locally and it is working.

**Comment by pholdridge** [comment]
@XeroIP is exactly right. His fix worked. Thank you!!!
I copied the PS1 file from this modules folder to my C:\temp folder and removed the signature at the bottom of the file.
C:\Program Files\WindowsPowerShell\Modules\MSIdentityTools\2.0.16 -> C:\temp.

This is quite embarrassing for the person who coded this PS1 file I'd imagine.

**Comment by jasoth** [comment]
Thanks @XeroIP and @pholdridge for reporting this issue. This was discovered to be a difference in Compare-Object behavior between Windows PowerShell 5 vs PS7. In addition to the WPS5 fix, I took this opportunity to standardize Mg command prereq checks for all commands with a common function as well.

While this particular issue should be fixed in #26 for the old Windows PowerShell 5 and I will be included in our next publish to PowerShell Gallery, I would highly encourage you to upgrade to PS7, as that version is where we focus our testing.

**Comment by pholdridge** [comment]
Upgrading to PS7 is your answer? Most users are on 5.1 because that ships with Windows 10. Nothing so far has forced us to upgrade to the latest PowerShell so we haven't.

**Comment by XeroIP** [comment]
We are using 5.1 deliberately, as we are running many runbooks in Azure Automation and 7.1 and 7.2 in that environment is in preview and is very, very buggy.

Thanks for getting this fixed!
